apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: flip-command
  labels:
    knative.dev/type: "function"
    eventing.knative.dev/autotrigger: "true"
  annotations:
    trigger.eventing.knative.dev/filter: |
      [{"type":"botless.bot.command.flip"}]
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/botless/commands/cmd/core/
            env:
            - name: TARGET
              value: "http://default-broker.default.svc.cluster.local"
            - name: STRICT_TYPE
              value: "botless.bot.command.flip"
